// Code generated by "stringer -type=ModelName"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultModel-1]
	_ = x[GPT4Turbo-2]
	_ = x[GPT4Vision-3]
}

const _ModelName_name = "DefaultModelGPT4TurboGPT4Vision"

var _ModelName_index = [...]uint8{0, 12, 21, 31}

func (i ModelName) String() string {
	i -= 1
	if i < 0 || i >= ModelName(len(_ModelName_index)-1) {
		return "ModelName(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ModelName_name[_ModelName_index[i]:_ModelName_index[i+1]]
}
