// Code generated by "stringer -type=ResponseFormat"; DO NOT EDIT.

package client

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoneSpecified-1]
	_ = x[JSONResponse-2]
	_ = x[TextResponse-3]
}

const _ResponseFormat_name = "NoneSpecifiedJSONResponseTextResponse"

var _ResponseFormat_index = [...]uint8{0, 13, 25, 37}

func (i ResponseFormat) String() string {
	i -= 1
	if i < 0 || i >= ResponseFormat(len(_ResponseFormat_index)-1) {
		return "ResponseFormat(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ResponseFormat_name[_ResponseFormat_index[i]:_ResponseFormat_index[i+1]]
}
